version: "3.9"

services:
  mysql:
    image: mariadb:11
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: entidadesTerritorialesColombia
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3309:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: --local-infile=1

  loader:
    image: mariadb:11
    container_name: mariadb_loader
    depends_on:
      - mysql
    volumes:
      - ./init:/init
      - ./repository:/repository
    entrypoint: >
      bash -c "
        echo 'Esperando a que MariaDB inicie...';
        until mariadb -h mysql -u root -proot123 -e 'SELECT 1;' > /dev/null 2>&1; do
          sleep 3;
        done;
        echo 'MariaDB lista. Ejecutando script...';
        mariadb -h mysql -u root -proot123 --local-infile=1 entidadesTerritorialesColombia < /init/01_schema.sql;
        echo 'Script ejecutado correctamente.';
      "