version: "3.9"

services:
  mysql:
    image: mariadb:11
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: entidadesTerritorialesColombia
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3309:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./repository:/var/lib/mysql-files
    command: --local-infile=1